apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: dev01-tkg-01
  namespace: dev01
spec:
  distribution:
    version: v1.16
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: pacific-gold-storage-policy
    workers:
      class: guaranteed-small
      count: 3
      storageClass: pacific-gold-storage-policy
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["10.40.0.0/16"]
      pods:
        cidrBlocks: ["10.240.0.0/16"]
